import type { Locale } from '@/i18n/dictionaries'

export const TRANSACTION_COPY = {
  id: {
    exportExcel: 'Export Excel',
    add: 'Tambah Transaksi',
    income: 'Pemasukan',
    expense: 'Pengeluaran',
    netCashflow: 'Net Cashflow',
    matchesFilter: 'Sesuai filter aktif',
    transactionCount: 'transaksi',
    todayTotal: 'Total hari ini',
    todayIncome: 'Pemasukan Hari Ini',
    todayExpense: 'Pengeluaran Hari Ini',
    filter: 'Filter',
    reset: 'Reset',
    type: 'Jenis',
    all: 'Semua',
    allCategories: 'Semua Kategori',
    category: 'Kategori',
    month: 'Bulan',
    allMonths: 'Semua bulan',
    fromDate: 'Dari Tanggal',
    toDate: 'Sampai Tanggal',
    pickDate: 'Pilih tanggal',
    pickStartFirst: 'Pilih tanggal mulai dulu',
    selected: 'transaksi dipilih',
    bulkHelp: 'Hapus massal akan menghitung ulang saldo dompet setelah transaksi dihapus.',
    cancelSelect: 'Batal Pilih',
    deleteSelected: 'Hapus Terpilih',
    searchPlaceholder: 'Cari kategori, dompet, deskripsi...',
    emptyTitle: 'Belum ada transaksi',
    deleteTitle: 'Hapus transaksi?',
    deleteDescription: 'Saldo dompet akan dihitung ulang setelah penghapusan.',
    deleteManyTitle: (count: number) => `Hapus ${count} transaksi?`,
    deleteManyDescription: 'Semua transaksi terpilih akan dihapus dan saldo dompet akan dihitung ulang.',
    deleteAll: 'Hapus Semua',
    deleted: 'Transaksi dihapus',
    deletedMany: (count: number) => `${count} transaksi dihapus`,
    detail: 'Detail',
    edit: 'Edit',
    delete: 'Hapus',
    cancel: 'Batal',
    action: 'Aksi',
    date: 'Tanggal',
    description: 'Deskripsi',
    amount: 'Nominal',
    editTitle: 'Edit Transaksi',
    updated: 'Transaksi diperbarui',
    merchantPlaceholder: 'cth: Indomaret',
    exportTitle: 'Export Transaksi ke Excel',
    exportDescription: 'Pilih periode dan filter sebelum mengunduh data transaksi.',
    download: 'Download .xlsx',
    byMonth: 'Per Bulan',
    byRange: 'Range Tanggal',
    pickMonth: 'Pilih Bulan',
    exportSuccess: 'File berhasil diunduh',
    invalidRange: 'Tanggal selesai tidak boleh lebih kecil dari tanggal mulai.',
    addTitle: 'Tambah Transaksi',
    addSubtitle: 'Catat pemasukan dan pengeluaran secara manual.',
    saved: 'Transaksi tersimpan',
    summary: 'Ringkasan',
    notSelected: 'Belum dipilih',
    wallet: 'Dompet',
    merchant: 'Merchant',
    tableLabels: {
      clearSearch: 'Bersihkan pencarian',
      show: 'Tampilkan',
      rows: 'data',
      showing: 'Menampilkan',
      entries: 'entri',
      previous: 'Sebelumnya',
      next: 'Berikutnya',
      page: 'Halaman',
    },
  },
  en: {
    exportExcel: 'Export Excel',
    add: 'Add Transaction',
    income: 'Income',
    expense: 'Expense',
    netCashflow: 'Net Cashflow',
    matchesFilter: 'Matches active filters',
    transactionCount: 'transactions',
    todayTotal: 'Today total',
    todayIncome: 'Income Today',
    todayExpense: 'Spending Today',
    filter: 'Filter',
    reset: 'Reset',
    type: 'Type',
    all: 'All',
    allCategories: 'All Categories',
    category: 'Category',
    month: 'Month',
    allMonths: 'All months',
    fromDate: 'From Date',
    toDate: 'To Date',
    pickDate: 'Pick date',
    pickStartFirst: 'Pick a start date first',
    selected: 'transactions selected',
    bulkHelp: 'Bulk delete will recalculate wallet balances after transactions are removed.',
    cancelSelect: 'Cancel Selection',
    deleteSelected: 'Delete Selected',
    searchPlaceholder: 'Search category, wallet, description...',
    emptyTitle: 'No transactions yet',
    deleteTitle: 'Delete transaction?',
    deleteDescription: 'Wallet balance will be recalculated after deletion.',
    deleteManyTitle: (count: number) => `Delete ${count} transactions?`,
    deleteManyDescription: 'All selected transactions will be deleted and wallet balances recalculated.',
    deleteAll: 'Delete All',
    deleted: 'Transaction deleted',
    deletedMany: (count: number) => `${count} transactions deleted`,
    detail: 'Detail',
    edit: 'Edit',
    delete: 'Delete',
    cancel: 'Cancel',
    action: 'Action',
    date: 'Date',
    description: 'Description',
    amount: 'Amount',
    editTitle: 'Edit Transaction',
    updated: 'Transaction updated',
    merchantPlaceholder: 'e.g. Indomaret',
    exportTitle: 'Export Transactions to Excel',
    exportDescription: 'Choose period and filters before downloading transaction data.',
    download: 'Download .xlsx',
    byMonth: 'By Month',
    byRange: 'Date Range',
    pickMonth: 'Pick Month',
    exportSuccess: 'File downloaded',
    invalidRange: 'End date cannot be earlier than start date.',
    addTitle: 'Add Transaction',
    addSubtitle: 'Record income and spending manually.',
    saved: 'Transaction saved',
    summary: 'Summary',
    notSelected: 'Not selected',
    wallet: 'Wallet',
    merchant: 'Merchant',
    tableLabels: {
      clearSearch: 'Clear search',
      show: 'Show',
      rows: 'rows',
      showing: 'Showing',
      entries: 'entries',
      previous: 'Previous',
      next: 'Next',
      page: 'Page',
    },
  },
} as const

export type TransactionCopy = typeof TRANSACTION_COPY.id

export function getTransactionCopy(locale: Locale): TransactionCopy {
  return TRANSACTION_COPY[locale] as TransactionCopy
}
